[tool.poetry]
name = "unit-converter"
version = "0.1.0"
description = ""
authors = ["satya25 <spnigam25@yahoo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
